### ISSUE TITLE
UndefKeywordError for keyword arguments

### ISSUE THREAD

**Issue by dpinol** [aviatesk/JET.jl#376] opened 2022-07-06 09:07 UTC
Create a package with just this
```
module kwarg
       f(;arg) = 3
end
```
With both julia 1.8.5 & 1.9.0-beta2 ~~run with julia 1.7.3 (it works fine with 1.8rc1)~~
`report_package("kwarg")`

You'll get this error with JET 0.6.24
```
═════ 1 possible error found ═════
┌ @ /home/dani/dev/julia/sandboxes/jet/kwarg/kwarg/src/kwarg.jl:2 throw(UndefKeywordError(:arg))
│ UndefKeywordError: keyword argument arg not assigned: throw(UndefKeywordError(:arg)::UndefKeywordError)::Union{}
```

**Comment by Roger-luo** [comment] 2023-02-24 21:06
I have a the same issue, I'm wondering why this is treated as an error? It should be valid?

**Comment by dpinol** [comment] 2023-03-30 09:42
hi, any news? Sorry for the spam, but this adds a lot of noise

**Comment by aviatesk** [comment] 2023-06-04 12:57
Duplicate of #487.

**Closed by aviatesk** 2023-06-04 12:57 UTC
