### ISSUE TITLE
TypeError when Running report_file on Custom Code

### ISSUE THREAD

**Issue by Satvik** [aviatesk/JET.jl#195] opened 2021-05-07 17:36 UTC
Hi,

I just started using JET, and so far I am able to get it to run on the demo file and produce the same results. However, when I try running it on my own code, I get a hard to understand error:

```
report_file("run_analysis_job_batch_portion.jl")
[toplevel-info] virtualized the context of Main (took 0.027 sec)
[toplevel-info] entered into run_analysis_job_batch_portion.jl
[toplevel-info]  exited from run_analysis_job_batch_portion.jl (took 76.381 sec)
ERROR: TypeError: in new, expected DataType, got Type{Tuple{Vararg{Any, N}} where N}
Stacktrace:
  [1] Base.Fix2(f::typeof(isequal), x::Type{Tuple})
    @ Base ./operators.jl:998
  [2] isequal(x::Type)
    @ Base ./operators.jl:1013
  [3] hash(A::Vector{Any}, h::UInt64)
    @ Base ./abstractarray.jl:2452
  [4] hash(x::JET.VirtualFrame, h::UInt64)
    @ JET ~/.julia/packages/JET/S4x7Z/src/JET.jl:323
  [5] hash
    @ ./hashing.jl:18 [inlined]
  [6] print_report(io::IOContext{IOBuffer}, report::JET.NoMethodErrorReport, config::JET.PrintConfig, wrote_linfos::Set{UInt64}, depth::Int64)
    @ JET ~/.julia/packages/JET/S4x7Z/src/print.jl:313
  [7] print_report(io::IOContext{IOBuffer}, report::JET.NoMethodErrorReport, config::JET.PrintConfig, wrote_linfos::Set{UInt64}, depth::Int64) (repeats 16 times)
    @ JET ~/.julia/packages/JET/S4x7Z/src/print.jl:319
  [8] print_report(io::IOContext{IOBuffer}, report::JET.NoMethodErrorReport, config::JET.PrintConfig, wrote_linfos::Set{UInt64})
    @ JET ~/.julia/packages/JET/S4x7Z/src/print.jl:306
  [9] (::JET.var"#109#110"{Vector{JET.InferenceErrorReport}, JET.PrintConfig})(io::IOContext{IOBuffer})
    @ JET ~/.julia/packages/JET/S4x7Z/src/print.jl:279
 [10] with_bufferring
    @ ~/.julia/packages/JET/S4x7Z/src/print.jl:165 [inlined]
 [11] print_reports(io::Base.TTY, reports::Vector{JET.InferenceErrorReport}, postprocess::Any; jetconfigs::Base.Iterators.Pairs{Symbol, IOContext{Base.TTY}, Tuple{Symbol}, NamedTuple{(:toplevel_logger,), Tuple{IOContext{Base.TTY}}}})
    @ JET ~/.julia/packages/JET/S4x7Z/src/print.jl:266
 [12] print_reports(io::Base.TTY, res::JET.VirtualProcessResult; jetconfigs::Base.Iterators.Pairs{Symbol, IOContext{Base.TTY}, Tuple{Symbol}, NamedTuple{(:toplevel_logger,), Tuple{IOContext{Base.TTY}}}})
    @ JET ~/.julia/packages/JET/S4x7Z/src/print.jl:112
 [13] #report_result#114
    @ ~/.julia/packages/JET/S4x7Z/src/JET.jl:467 [inlined]
 [14] report_file(io::Base.TTY, filename::String; jetconfigs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ JET ~/.julia/packages/JET/S4x7Z/src/JET.jl:520
 [15] report_file(io::Base.TTY, filename::String)
    @ JET ~/.julia/packages/JET/S4x7Z/src/JET.jl:507
 [16] report_file(args::String; jetconfigs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ JET ~/.julia/packages/JET/S4x7Z/src/JET.jl:522
 [17] report_file(args::String)
    @ JET ~/.julia/packages/JET/S4x7Z/src/JET.jl:522
 [18] top-level scope
    @ REPL[5]:1
```

I get this error on Julia 1.6.0 and 1.6.1, on macos or Ubuntu. I get a similar error when setting `analyze_from_definitions=true`:

```
[toplevel-info] virtualized the context of Main (took 0.003 sec)
[toplevel-info] entered into run_analysis_job_batch_portion.jl
[toplevel-info]  exited from run_analysis_job_batch_portion.jl (took 2.653 sec)
[toplevel-info] analyzing from top-level definitions ... 4/4
ERROR: TypeError: in new, expected DataType, got Type{Tuple{Vararg{Any, N}} where N}
Stacktrace:
  [1] Base.Fix2(f::typeof(isequal), x::Type{Tuple})
    @ Base ./operators.jl:998
  [2] isequal(x::Type)
    @ Base ./operators.jl:1013
  [3] hash(A::Vector{Any}, h::UInt64)
    @ Base ./abstractarray.jl:2452
  [4] hash(x::JET.VirtualFrame, h::UInt64)
    @ JET ~/.julia/packages/JET/S4x7Z/src/JET.jl:323
  [5] hash
    @ ./hashing.jl:18 [inlined]
  [6] print_report(io::IOContext{IOBuffer}, report::JET.NoMethodErrorReport, config::JET.PrintConfig, wrote_linfos::Set{UInt64}, depth::Int64)
    @ JET ~/.julia/packages/JET/S4x7Z/src/print.jl:313
  [7] print_report(io::IOContext{IOBuffer}, report::JET.NoMethodErrorReport, config::JET.PrintConfig, wrote_linfos::Set{UInt64}, depth::Int64) (repeats 16 times)
    @ JET ~/.julia/packages/JET/S4x7Z/src/print.jl:319
  [8] print_report(io::IOContext{IOBuffer}, report::JET.NoMethodErrorReport, config::JET.PrintConfig, wrote_linfos::Set{UInt64})
    @ JET ~/.julia/packages/JET/S4x7Z/src/print.jl:306
  [9] (::JET.var"#109#110"{Vector{JET.InferenceErrorReport}, JET.PrintConfig})(io::IOContext{IOBuffer})
    @ JET ~/.julia/packages/JET/S4x7Z/src/print.jl:279
 [10] with_bufferring
    @ ~/.julia/packages/JET/S4x7Z/src/print.jl:165 [inlined]
 [11] print_reports(io::Base.TTY, reports::Vector{JET.InferenceErrorReport}, postprocess::Any; jetconfigs::Base.Iterators.Pairs{Symbol, Any, Tuple{Symbol, Symbol}, NamedTuple{(:analyze_from_definitions, :toplevel_logger), Tuple{Bool, IOContext{Base.TTY}}}})
    @ JET ~/.julia/packages/JET/S4x7Z/src/print.jl:266
 [12] print_reports(io::Base.TTY, res::JET.VirtualProcessResult; jetconfigs::Base.Iterators.Pairs{Symbol, Any, Tuple{Symbol, Symbol}, NamedTuple{(:analyze_from_definitions, :toplevel_logger), Tuple{Bool, IOContext{Base.TTY}}}})
    @ JET ~/.julia/packages/JET/S4x7Z/src/print.jl:112
 [13] #report_result#114
    @ ~/.julia/packages/JET/S4x7Z/src/JET.jl:467 [inlined]
 [14] report_file(io::Base.TTY, filename::String; jetconfigs::Base.Iterators.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:analyze_from_definitions,), Tuple{Bool}}})
    @ JET ~/.julia/packages/JET/S4x7Z/src/JET.jl:520
 [15] report_file(args::String; jetconfigs::Base.Iterators.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:analyze_from_definitions,), Tuple{Bool}}})
    @ JET ~/.julia/packages/JET/S4x7Z/src/JET.jl:522
 [16] top-level scope
    @ REPL[8]:1
```

and also when using `report_package`.

Any tips on how to start debugging this?

**Comment by aviatesk** [comment] 2021-05-07 17:42
Looks like duplicate of https://github.com/aviatesk/JET.jl/issues/173 (see https://github.com/aviatesk/JET.jl/issues/173#issuecomment-826028189) ?

Probably this won't happen if you're using nightly Julia or source build.

**Closed** 2021-05-08 02:38 UTC
